#!/usr/bin/ruby

  #############################################################################
 #
# Stochastic Drone
#
# Creates a midi file that has no time signature. Drone notes trigger
# in a sequence (maybe pseudo random) at random times. Best midi programs
# to use are those with long release times, long pads.
#
# Based on the tampura method by John Pitts in "How to Play Indian Sitar Ragas
# on a Piano"
# 
require 'distribution'
require 'midilib/sequence'
require 'midilib/consts'
require 'optparse'
include MIDI

seq = Sequence.new # Need a sequencer for output


  #############################################################################
 #
# Grace note class
#
class Grace
  attr_reader :first, :second

  def to_ary; [first, second] end
  alias_method :to_a, :to_ary

  private

  attr_writer :first, :second

  def initialize(first, second)
    self.first, self.second = first, second
  end

  class << self; alias_method :[], :new end
end


  #############################################################################
 #
# Patterns from John Pitts
#
classical  = [-5, 0, 0, -12]                     # works for just about anything
alternate  = [-7, 0, 0, -12]                     # works for asian scales or sus tonic chord pieces
latangi    = [-5, -1,  0, 0, -12, -5, 2, 0, -12] # major 7, 9
todi       = [-4,  1,  0, -12]                   # Blues complement
vachaspati = [-5, -2, 0, -12]                    # Mixolydian
patdeep    = [-5, -1, 0, -12, 3]                 # Minor 
desh       = [-5, -1, 0, -12, -5, 0, 2, 0, -12]  # Sharp 6
malhar     = [-5, 0, 0, -12, -5, 2, 0, 0, -12]   # 9
chayanat   = [-5, 2, -12, -5, 4, 2, -12]         # tritone


bliss          = [ 0, 7, 9, 7, 9, [0, 2, 4, 5], Grace.new(-12, -7), [-10, -19, -24]] # straight (bliss)
mountain_stream= [-5, 0, 0, 2, 0, -2, 0, -12]        # minor 
little_girl    = [-5, 0, 0, -12, -1, 0, [-5], [4], [2], [-1]] 
landscape      = [ 7, 11, 12, 12, 14, [7], [9], [11], Grace.new(-5, 0),  [-5], [-12], [-17]] # sweeping landscape
wise_man       = [-5, -2, 0, 0, [2], [4], [-10], -12] # major
gazelle        = [-5, [-4], 0, 0, [1], [4], [-1], -12] # occasional head butts
moonlight      = [ 7, 12, 14, 10, 12, [8, 10, -2], 0] 
waiting_bride  = [-5, 0, 0, 2, [2, 3, 5], -12]
sleep          = [-7, -5, -2, 0, -12, -7, -5, 0, 2, -2, 0, -12]
pollen_breeze  = [ 7, 8, [11], 8, [6], 0, [1] ]
elegant_mischief=[ [-7], -8, -7, Grace.new(1, 0), 0, -12]
saffron_aroma  = [-5, [0], [0, 1], 0, -12]
ruddy_goose    = [-5, 0, 0, -12, 4, Grace.new(1, 0), -12]
intense_coffee = [-5, [-1], 0, 0, -12]
morning_sun    = [-5, 4, [1], Grace.new(-2, 0), [0], Grace.new(-2, 0), 
                  [-11], [-14], -12, -8]
mourning       = [-5, [-2], 0, 0, -11, -12, -5, 1, 0, -12]
full_of_hope   = [-12, -5, Grace.new(0, 2), Grace.new(2, 3),
                  [Grace.new(-4, -2)], [-14], [Grace.new(-2, 0)] ]
lady_lost_in_forest = [-16, [Grace.new(-17,-16)], -11, -12, -24]
lunchtime_bell = [-17, -12, -12, -24]

# Note, for flowing honey, stealing_my_heart set
# optional = [true, false, false, false]
flowing_honey  = [-5, [-3,-1,0], 0, 2, [6, 7, 9, 11, 12], -12, [-10],
                  -5, [-3,-1,0], 0, 2, [6, 7, 9, 11, 12], -12,
                  0, -5, [-3,-1,0], -12, [6,7,9,11,12,-10], 2,
                  -5, [-3,-1,0], 0, 2, [6, 7, 9, 11, 12], -12, [-10],
                  -5, [-3,-1,0], 0, -12, [6, 7, 9, 11, 12], 2,
                  0, -5, [-3,-1,0], 2, [6,7,9,11,12,-10], -12,]
stealing_my_heart = [ [-24], [-17], -12, 7, 2, [-24], 8, 0, 10, 6, 12]
#

beautiful_hair = [-5, -4, 0, 2, 0, 2, 2, 4, 2, 4, Grace.new(-17, -12),
                  [-17, -24, -29]]
from_the_east  = [-5, 0, -12, -4, [1, 4]]
satisfaction   = [-15, -11, -12, -24, -13, -12, -12, -24]

  #############################################################################
 #
# Pollen Breeze has an opening drone that swells with 2 parts, an upper and
# lower. Use this program with repeat set to 1, and create the upper and lower
# as an intro, with the same tonic, tempo and random number generator
# Maybe add some swells in post
#
# This is followed by the drone above, and the melody is allowed to develop
#
na = nil
pollen_br_lwr  = [ 7, 8, 8, 0, 7, 8, 8, 0, 7, 8, 8, 0, 7, 8, 8, 0, 
                  7, 8, 8,11, 0, 7, 8, 8,11, 1, 0,
                  7, 8, 8,11, 1, 8, 0, 7, 8, 8,11, 1, 8, 0, 5,
                  7, 8, 8,11, 1, 8, 0, 5]
pollen_br_up  = [na,na,na,na,na,na,na,na,20,13,12,20,13,12,20,13,
                 12,20,19,13,12,20,19,13,12,20,19,
                 13,11,12,20,19,13,11,12,20,19,13,11,12,16,20,
                 19,13,11,12,15,20,13,12]

patterns = [classical, alternate, latangi, todi, vachaspati, patdeep, desh, malhar, chayanat,
            bliss, mountain_stream, little_girl, landscape, wise_man, gazelle, moonlight,
            waiting_bride, sleep, pollen_breeze, elegant_mischief, saffron_aroma,
            ruddy_goose, intense_coffee, morning_sun, mourning, full_of_hope, 
            lady_lost_in_forest, lunchtime_bell, flowing_honey, stealing_my_heart,
            beautiful_hair, from_the_east, satisfaction, pollen_br_lwr, pollen_br_up]

  #############################################################################
 #
# Parse command line options
#
options = {
  :pattern => 0,
  :tonic   => 60,     # Middle-C
  :bpm     => 120,
  :rng     => Distribution::Exponential.rng(1),
  :note_len=> 4*seq.note_to_delta('quarter'),
  :repeats => 24,
  :program => 89, # General Midi Pad
  :optional=> [true, false, false, false], # 1 in 4 chance
  :filename=> 'stoch_drone.mid',
  :grace   => 32 # Division of note_len to use for grace note
}

OptionParser.new do |opts|
  opts.banner = "Usage: gendrone [options]"
  
  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end

  opts.on("-aARRANGEMENT", "--arrangement=ARRANGEMENT", "Arrangement Number (0-34). Default 0. See: `gendrone -d`") do |n|
    n = n.to_i
    if n < 0 or n > 34 
      puts "Arrangement number must be in the range 0-34"
      exit
    end
    options[:pattern] = n
  end  

  opts.on("-tTONIC", "--tonic=TONIC", "MIDI tonic note. Default 60, i.e. middle C.") do |t|
    t = t.to_i
    if t < 0 or t > 127 
      puts "Tonic must be in the range 0-127"
      exit
    end
    options[:tonic] = t
  end

  opts.on("-bBPM", "--bpm=BPM", "Beats per minute info. Default 120.") do |b|
    b = b.to_i
    if b < 1 or b > 1000
      puts "BPM must be in the range 1-1000"
      exit
    end
    options[:bpm] = b
  end

  opts.on("-fFILENAME", "--filename=FILENAME", "Output filename. Default 'stoch_drone.mid'.") do |f|
    options[:filename] = f
  end

  opts.on("-iITERATIONS", "--iterations=ITERATIONS", "Iteration count of pattern. Default 24.") do |i| 
    i = i.to_i
    if i<1 
      puts "ITERATIONS must be positive"
      exit
    end
    options[:repeats] = i
  end

  opts.on("-lNOTE_LEN", "--length=NOTE_LEN", "Average length of note in terms of quarter note. Default 4.") do |l|
    l = l.to_f
    if l<0 or l > 100
      puts "NOTE_LEN must be greater than 0 and less than or equal to 100."
      exit
    end
    options[:note_len] = (l*seq.note_to_delta('quarter')).round
  end

  opts.on("-oOPTIONAL", "--optional=OPTIONAL", "Optional notes as 1 in OPTIONAL odds. Default 4.") do |o|
    o = o.to_i
    if o < 1 or o > 100
      puts "OPTIONAL must be between 1 and 100"
      exit
    end
    options[:optional] = Array.new(o, false)
    options[:optional][0] = true
  end

  opts.on("-pPROGRAM", "--program=PROGRAM", "MIDI Program for track. Default 89 GM pad.") do |p|
    p = p.to_i
    if p < 1 or p > 128
      puts "PROGRAM must be between 1 and 128"
      exit
    end
    options[:program] = p
  end

  opts.on("-gGRACE", "--grace=GRACE", "Division of note length to use for grace note. Default 32.") do |g|
    g = g.to_i
    if g < 1 or g > 128
      puts "GRACE must be between 1 and 128"
      exit
    end
    options[:grace] = g
  end

  opts.on("-rRNG", "--random=RNG", "Random number generator. Options: 'none', 'exp', 'gamma2', 'gamma9', or 'uniform'. Default 'exp'.") do |r|
    # All of these have a mean of 1.0
    if r == 'none'
      options[:rng] = lambda {1}
    elsif r == 'exp'
      options[:rng] = Distribution::Exponential.rng(1.0) 
    elsif r == 'gamma2'
      options[:rng] = lambda {Distribution::Gamma.p_value(rand(), 2.0, 2.0)/4.0}
    elsif r == 'gamma9'
      options[:rng] = lambda {Distribution::Gamma.p_value(rand(), 9.0, 0.5)/4.5}
    elsif r == 'uniform'
      options[:rng] = lambda {rand()*2.0}
    else
      puts "Unhandled RNG category"
      exit
    end
  end

  opts.on("-d", "--describe", "Describe programmed arrangements.") do
    puts  <<-DESC
The descriptions use the Nashville Number system, denoting the tonic as 1. The drone arrangements programmed are as follows:

0. Classical. The classical tampura drone tuning. Simple 4 note pattern. Works with any scale having a tonic and fifth.
1. Alternate. A lesser used tampura drone tuning. Instead of 5th, contains the 4th.
2. Latangi. A simpler version of 11. Little Girl below. Mood: playful. Intended scale 1 2 3 #4 5 b6 7.
3. Todi A simpler version of 26. Lady Lost in the Forest. Mood: unsettled, fearful. Intended scale 1 b2 b3 #4 (5) b6 7. 
4. Vachaspati. A simpler version of 13. Wise Old Man. Mood: taking it in stride. Intended scale 1 2 3 #4 5 6 b7. 
5. Patdeep. A simpler version of Stealing My Heart. Mood: yearing. Intended scale 1 2 b3 3 4 5 6 7
6. Desh. A simpler version of 12. Sweeping Landscape. Mood: majestic joy. Intended scale 1 2 3 4 5 6 b7/7
7. Malhar or Monsoon. Mood: murkey, causing rain. Intended scale 1 2 b3 4 5 6 b7/7
8. Chayanta or Glimpse of Shadow. Mood: sweet. Intended scale 1 2 3 4 5 6 7
9. Bliss or Kalyani. Mood: Peaceful. Intended scale 1 2 3 #4 5 6 7
10. Mountain Stream or Hemavati. Mood: Aredently Thoughtful. Intended scale 1 2 b3 #4 5 6 b7
11. Little Girl or Latangi. Mood: Playful. Intended scale 1 2 3 #4 5 b6 7.
12. Sweeping Landscape or Desh. Mood: Majestic Joy. Intended scale 1 2 3 4 5 6 b7/7
13. Wise Old Man or Vachaspati. Mood: Taking it in Stride. Intended scale 1 2 3 #4 5 6 b7
14. Gazelle or Gazellish. Mood: Sprightly. Intended scale 1 b2/2 b3/3 4 5 b6 b7/7. Scale switches flexibly, but not chromatically.
15. Moonlight or Kalavati. Mood: Light Romantic or Playful. Intended scale 1 2 3 4 5 6 b7. Mixolydian
16. Waiting Bride or Bagesri. Mood: Light Romantic. Intended scale 1 2 b3 4 5 6 b7. 
17. Sleep or Neenda. Mood: Melancholy, Mysterious. Intended scale 1 b2 b3 4 5 b6 b7
18. Pollen on the Breeze or Paraj.  Mood: Peaceful, ecstatic. Intended scale 1 b2 3 #4 5 b6 7
19. Elegant Mischief or Lalit. Mood: Ludicrous, mischievous. Intended scale 1 b2 3 4 b5 b6 7. Mischief between 4 and b5. 
20. Aroma of Saffron or Jogiya kalingra. Mood: Wonderous. Intended scale 1 b2 3 4 5 b6 7
21. Ruddy Goose or Chakravak. Mood: Ridiculous, silly, playful. Intended scale 1 b2 3 4 5 6 b7
22. Intense Coffee or Kofi. Mood: Magical, moody and intense. Intended scale 1 2 b3 #4 5 b6 7
23. Morning Sun or Suraja. Mood: Peaceful and warm. Intended scale 1 b2 3 #4 5 6 b7
24. Mourning or Bilaskhani Todi. Mood: Mourning, grieving, devotional. Intended scale 1 b2 b3 4 5 b6 b7
25. Full of Hope or Asavari. Mood: Heroic, Striving, Conviction. Intended scale 1 2 b3 4 5 b6 b7
26. Lady Lost in the Forest or Todi. Mood: Fearful. Intended scale 1 b2 b3 #4 (5) b6 7
27. Lunchtime Bell or Gaud Sarang. Mood: Peaceful, satisfied. Intended scale 1 2 3 4 5 6 7. Will work with any with any having a natural 5th.
28. Flowing with Honey or Madhuvanti. Same as 1 but an octave lower. Mood: Soothing, magical. Intended scale 1 2 b3 #4 5 6 7
29. Stealing my Heart or Patdeep. Mood: Yearing, falling in love. Intended scale 1 2 b3 4 5 b6 7
30. Beautiful Hair or Charukesi. Mood: Determined, nostalgic. Intended scale 1 2 3 4 5 b6 (b7)
31. From the East or Purvi. Mood: Light, romantic, charming, graceful. Intended scale 1 b2 3 #4 5 b6 7
32. Satisfaction. Mood: Humourous, magical. Intended scale 1 b2 3 #4 (5) 6 7
33. Special lower intro track to 18 Pollen. Use 1 iteration and mix with 34. 
34. Special upper intro track to 18 Pollen. Use 1 iteration and mix with 33.
DESC
  end

end.parse!


tampura = patterns[options[:pattern]]


  #############################################################################
 #
# Construct the midi track from the parameters
#
# Create a first track for the sequence. This holds tempo events and stuff
# like that.
track = Track.new(seq)
seq.tracks << track
track.events << Tempo.new(Tempo.bpm_to_mpq(options[:bpm]))
track.events << MetaEvent.new(META_SEQ_NAME, 'Stochastic Drone')

# Create a track to hold the notes. Add it to the sequence.
track = Track.new(seq)
seq.tracks << track
track.name = 'StochDrone'
track.instrument = GM_PATCH_NAMES[options[:program]-1]

# Add events to the track: a major scale. Arguments for note on and note off
# constructors are channel, note, velocity, and delta_time. Channel numbers
# start at zero. We use the new Sequence#note_to_delta method to get the
# delta time length of a single quarter note.
track.events << ProgramChange.new(0, options[:program], 0)
pause = 0
options[:repeats].times do
  tampura.each do |offset|
    if offset.class == Grace   or 
       offset.class == Integer 
      note = offset
    elsif offset.class == NilClass
      note = nil
      pause += (options[:note_len]*rng.call).to_i
    else 
      if options[:optional].sample
        note = offset.sample       
      else
        note = nil
      end
    end
    unless note.class == NilClass
      if note.class == Grace
         track.events << NoteOn.new(0, options[:tonic] + note.first, 100, pause)
         pause=0
         track.events << NoteOff.new(0, options[:tonic] + note.first, 100, (options[:note_len]/options[:grace]).to_i)
         note = note.second
      end
      track.events << NoteOn.new(0, options[:tonic] + note, 100, pause)
      pause=0
      track.events << NoteOff.new(0, options[:tonic] + note, 100,
        (options[:note_len] * options[:rng].call).to_i)
    end
  end
end

File.open(options[:filename], 'wb') { |file| seq.write(file) }
